apiVersion: v1
kind: Service

metadata:
  name: spring-service

spec:
  type: NodePort

  selector:
    app: backend-app

  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30000
