apiVersion: v1
kind: Service

metadata:
  name: admin-spring-service

spec:
  type: NodePort

  selector:
    app: admin-backend-app

  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
