apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db

  template:
    metadata:
      labels:
        app: mysql-db

    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: mysql-root-password

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: server-secret
                  key: mysql-database

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
